--- 

- name: Create servable folders
  file:
    path: /var/www/www.aychedee.com/_build
    state: directory

- name: Create csr folders
  file:
    path: /etc/ssl/csr
    owner: www-user
    mode: 0755
    state: directory

- name: Create certs folders
  file:
    path: /etc/ssl/certs
    owner: www-user
    mode: 0755
    state: directory

- name: Ensure we have large ephemeral key for nginx
  command: openssl dhparam -out /etc/ssl/private/dhparam.pem 4098
  args:
      creates: /etc/ssl/private/dhparam.pem

- name: Sync built html
  synchronize:
    src: ../www.aychedee.com/_build/
    dest: /var/www/www.aychedee.com/_build/

- name: Sync presentations
  synchronize:
    src: ../www.aychedee.com/_presentations/
    dest: /var/www/www.aychedee.com/_presentations/

- name: Sync static files
  synchronize:
    src: ../www.aychedee.com/static/
    dest: /var/www/www.aychedee.com/static/

- name: Copy keybase file
  copy:
    src: ../www.aychedee.com/keybase.txt
    dest: /var/www/www.aychedee.com/keybase.txt
    mode: 0644

- name: Update www.aychedee.com nginx config
  copy:
    src: aychedee.conf
    dest: /etc/nginx/sites-enabled/www.aychedee.com
    mode: 0644
  notify:
    - restart nginx

- name: Generate key/CSR for aychedee.com
  command: openssl req -nodes -newkey rsa:2048 -keyout /etc/ssl/private/aychedee.com.key -out /etc/ssl/csr/aychedee.com.csr -subj "/C=GB/ST=Greater London/L=London/O=aychedee/OU=Web Infrastructure/CN=www.aychedee.com"
  args:
      creates: /etc/ssl/csr/aychedee.com.csr

- name: Generate letsencrypt account key for aychedee.com
  command: openssl genrsa -out /etc/ssl/private/aychedee.com.account.key
  args:
      creates: /etc/ssl/private/aychedee.com.account.key

- name: Get challenge information from letsencrypt
  acme_certificate:
    acme_version: 2
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    account_key: /etc/ssl/private/aychedee.com.account.key
    csr: /etc/ssl/csr/aychedee.com.csr
    dest: /etc/ssl/certs/aychedee.com.pem
  register: aychedee_com_challenge

- name: Display challenge variable
  debug: msg={{ aychedee_com_challenge }}

- name: Copy challenge variable from letsencrypt
  copy:
    dest: /var/www/www.aychedee.com/static/acme-challenge/{{ aychedee_com_challenge['challenge_data']['www.aychedee.com']['http-01']['resource'].split('/')[-1] }}
    content: "{{ aychedee_com_challenge['challenge_data']['www.aychedee.com']['http-01']['resource_value'] }}"
  when: aychedee_com_challenge is changed

- name: Setup ssl certificate
  acme_certificate:
    acme_version: 2
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    account_key: /etc/ssl/private/aychedee.com.account.key
    csr: /etc/ssl/csr/aychedee.com.csr
    dest: /etc/ssl/certs/aychedee.com.pem
    data: "{{ aychedee_com_challenge }}"
  notify:
    - restart nginx

- name: Put letsencrypts certificate chain into place
  file: 
    dest: /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem
    src: /home/ubuntu/lets-encrypt-x3-cross-signed.pem
    mode: 0644
    owner: root
    group: root

- name: Created chained certificate 
  shell: cat /etc/ssl/certs/aychedee.com.pem /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem  > /etc/ssl/certs/aychedee.com.chained.pem
  when: aychedee_com_challenge is changed
  changed_when: False

