--- 

- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install common packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-pip
