---

- hosts: aychedee
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - include_tasks: common.yml
    - include_tasks: squid.yml
    - include_tasks: nginx.yml
    - include_tasks: aychedee.com.yml
      tags: [aychedee]
    - include_tasks: interpretthis.org.yml
      tags: [interpretthis]

  handlers:

    - name: restart squid
      service: name=squid state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart pptpd
      service: name=pptpd state=restarted

    - name: restart uwsgi
      service: name=emperor.uwsgi.service state=restarted
