---

- hosts: aychedee
  remote_user: ubuntu
  sudo: yes
  tasks:
    - include: common.yml
    - include: squid.yml
    - include: nginx.yml
    - include: aychedee.com.yml
    - include: interpretthis.org.yml

  handlers:
    - name: restart squid
      service: name=squid state=restarted

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

  handlers:
    - name: restart uwsgi
      service: name=emperor.uwsgi.service state=restarted
