--- 
- hosts: aychedee
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  roles:
  - Stouts.openvpn

  vars:
    openvpn_use_pam: yes
    openvpn_clients: [myvpn]
    openvpn_use_pam_users:
      - { name: hansel, password: "shady little secrets" }
      - { name: jennifer, password: "private munchy monster" }
    openvpn_unified_client_profiles: yes
